//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestChat.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatRoomUser
    {
        public long ChatRoomUserID { get; set; }
        public Nullable<long> ChatRoomID { get; set; }
        public Nullable<long> UserID { get; set; }
    
        public virtual ChatRoom ChatRoom { get; set; }
        public virtual User User { get; set; }
    }
}
