//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestChat.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatRoom
    {
        public ChatRoom()
        {
            this.ChatRoomUsers = new HashSet<ChatRoomUser>();
        }
    
        public long ChatRoomID { get; set; }
        public string ChatRoomName { get; set; }
    
        public virtual ICollection<ChatRoomUser> ChatRoomUsers { get; set; }
    }
}
